import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display } from "next/font/google";
import { NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages } from 'next-intl/server';
import { Providers } from "@/components/providers";
import { Header, Footer } from "@/components/navigation";
import { localeConfig, type Locale } from "@/i18n/config";
import "./globals.css";

// Font configuration - matches fractional.quest design system
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
  preload: true,
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
  preload: true,
});

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  display: "swap",
  preload: true,
});

export const metadata: Metadata = {
  title: {
    default: "Fractional Executive Agency | C-Suite Roles £900-£1,500/day",
    template: "%s | Fractional Quest"
  },
  description: "Fractional executive agency matching C-suite talent with companies. Find roles paying £1,200-£2,500/day.",
  metadataBase: new URL("https://fractional.quest"),
  alternates: {
    canonical: "/",
  },
  openGraph: {
    siteName: "Fractional Quest",
    type: "website",
    locale: "en_GB",
  },
  twitter: {
    card: "summary_large_image",
  },
  appleWebApp: {
    title: "Fractional Quest",
    capable: true,
    statusBarStyle: "default",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Get locale from middleware (defaults to 'uk')
  const locale = await getLocale() as Locale;
  const messages = await getMessages();
  const config = localeConfig[locale];

  return (
    <html lang={config.language} suppressHydrationWarning>
      <head>
        {/* Preconnect to Google Fonts for faster font loading */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        {/* Preconnect to Unsplash for job card images */}
        <link rel="preconnect" href="https://images.unsplash.com" />
        <link rel="dns-prefetch" href="https://images.unsplash.com" />
        {/* Favicon - generated by RealFaviconGenerator */}
        <link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96" />
        <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
        <link rel="shortcut icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <meta name="apple-mobile-web-app-title" content="Fractional Quest" />
        <link rel="manifest" href="/site.webmanifest" />
        {/* WebSite Schema for Google site name */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "WebSite",
              "@id": "https://fractional.quest/#website",
              "name": "Fractional Quest",
              "alternateName": ["Fractional Quest", "FJQ"],
              "url": "https://fractional.quest",
              "description": "Fractional executive agency specialising in C-suite talent matching and recruitment.",
              "publisher": {
                "@type": "Organization",
                "@id": "https://fractional.quest/#organization",
                "name": "Fractional Quest",
                "url": "https://fractional.quest"
              },
              "potentialAction": {
                "@type": "SearchAction",
                "target": {
                  "@type": "EntryPoint",
                  "urlTemplate": "https://fractional.quest/search?q={search_term_string}"
                },
                "query-input": "required name=search_term_string"
              }
            })
          }}
        />
        {/* EmploymentAgency Schema for recruitment agency positioning */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "EmploymentAgency",
              "@id": "https://fractional.quest/#employment-agency",
              "name": "Fractional Quest",
              "description": "Fractional executive agency for C-suite talent matching. Specialising in fractional CFO, CTO, CMO, COO, and other executive roles.",
              "url": "https://fractional.quest",
              "areaServed": [
                { "@type": "Country", "name": "United Kingdom" },
                { "@type": "Country", "name": "United States" },
                { "@type": "Country", "name": "Australia" },
                { "@type": "Country", "name": "New Zealand" }
              ],
              "serviceType": ["Executive Recruitment", "Fractional Executive Hiring", "C-Suite Recruitment"],
              "slogan": "10-15% fees vs 25-30% industry standard",
              "knowsAbout": ["Fractional CFO", "Fractional CTO", "Fractional CMO", "Interim Executive", "C-Suite Hiring"]
            })
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${playfair.variable} antialiased bg-white text-gray-900`}
      >
        <NextIntlClientProvider messages={messages} locale={locale}>
          <Providers>
            <Header />
            <main className="pt-16 lg:pt-20">
              {children}
            </main>
            <Footer />
          </Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
