import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display } from "next/font/google";
import { Providers } from "@/components/providers";
import { Header, Footer } from "@/components/navigation";
import "./globals.css";
import "@copilotkit/react-ui/styles.css";

// Font configuration - matches fractional.quest design system
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
  preload: true,
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
  preload: true,
});

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  display: "swap",
  preload: true,
});

export const metadata: Metadata = {
  title: {
    default: "Fractional Jobs | Fractional Jobs Quest",
    template: "%s | Fractional Jobs Quest"
  },
  description: "AI-powered fractional job search platform. Find executive roles paying £1,200-£2,500/day.",
  metadataBase: new URL("https://fractional.quest"),
  alternates: {
    canonical: "/",
  },
  openGraph: {
    siteName: "Fractional Jobs Quest",
    type: "website",
    locale: "en_GB",
  },
  twitter: {
    card: "summary_large_image",
  },
  appleWebApp: {
    title: "Fractional Jobs Quest",
    capable: true,
    statusBarStyle: "default",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* Preconnect to Google Fonts for faster font loading */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        {/* Favicon - generated by RealFaviconGenerator */}
        <link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96" />
        <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
        <link rel="shortcut icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <meta name="apple-mobile-web-app-title" content="Fractional Jobs Quest" />
        <link rel="manifest" href="/site.webmanifest" />
        {/* WebSite Schema for Google site name */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "WebSite",
              "@id": "https://fractional.quest/#website",
              "name": "Fractional Jobs Quest",
              "alternateName": ["Fractional Quest", "FJQ"],
              "url": "https://fractional.quest",
              "description": "AI-powered fractional job search platform. Find executive roles paying £1,200-£2,500/day.",
              "publisher": {
                "@type": "Organization",
                "@id": "https://fractional.quest/#organization",
                "name": "Fractional Jobs Quest",
                "url": "https://fractional.quest"
              },
              "potentialAction": {
                "@type": "SearchAction",
                "target": {
                  "@type": "EntryPoint",
                  "urlTemplate": "https://fractional.quest/search?q={search_term_string}"
                },
                "query-input": "required name=search_term_string"
              }
            })
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${playfair.variable} antialiased bg-white text-gray-900`}
      >
        <Providers>
          <Header />
          <main className="pt-16 lg:pt-20">
            {children}
          </main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
