// Role configuration for 42 new C-suite roles
// Used by generate-mdx-pages.ts to create MDX content in Neon

export interface RoleConfig {
  acronym: string
  fullTitle: string
  urlSlug: string // base slug (e.g., 'fractional-caio')
  department: string
  accentColor: string
  dayRateMin: number
  dayRateMax: number
  avgDayRate: number
  tier: 1 | 2 | 3
  jobSearchTerms: string[] // SQL ILIKE patterns
  relatedRoles: string[] // existing role slugs for internal linking
}

export const ROLES: RoleConfig[] = [
  // === TIER 1: High Priority (11 roles) ===
  {
    acronym: 'CAIO',
    fullTitle: 'Chief AI Officer',
    urlSlug: 'fractional-caio',
    department: 'Technology',
    accentColor: 'blue',
    dayRateMin: 1200,
    dayRateMax: 2500,
    avgDayRate: 1800,
    tier: 1,
    jobSearchTerms: ['%ai officer%', '%caio%', '%artificial intelligence%officer%', '%head of ai%'],
    relatedRoles: ['fractional-cto', 'fractional-cio-chief-information-officer'],
  },
  {
    acronym: 'CDO',
    fullTitle: 'Chief Data Officer',
    urlSlug: 'fractional-cdo-chief-data-officer',
    department: 'Technology',
    accentColor: 'blue',
    dayRateMin: 1000,
    dayRateMax: 2200,
    avgDayRate: 1500,
    tier: 1,
    jobSearchTerms: ['%data officer%', '%cdo%data%', '%head of data%'],
    relatedRoles: ['fractional-cto', 'fractional-caio'],
  },
  {
    acronym: 'CIO',
    fullTitle: 'Chief Information Officer',
    urlSlug: 'fractional-cio-chief-information-officer',
    department: 'Technology',
    accentColor: 'blue',
    dayRateMin: 1100,
    dayRateMax: 2300,
    avgDayRate: 1600,
    tier: 1,
    jobSearchTerms: ['%information officer%', '%cio%', '%head of it%', '%it director%'],
    relatedRoles: ['fractional-cto', 'fractional-ciso'],
  },
  {
    acronym: 'CCO',
    fullTitle: 'Chief Commercial Officer',
    urlSlug: 'fractional-cco-chief-commercial-officer',
    department: 'Sales',
    accentColor: 'orange',
    dayRateMin: 1000,
    dayRateMax: 2000,
    avgDayRate: 1400,
    tier: 1,
    jobSearchTerms: ['%commercial officer%', '%chief commercial%', '%head of commercial%'],
    relatedRoles: ['fractional-cro', 'fractional-cgo'],
  },
  {
    acronym: 'CDO',
    fullTitle: 'Chief Digital Officer',
    urlSlug: 'fractional-cdo-chief-digital-officer',
    department: 'Technology',
    accentColor: 'blue',
    dayRateMin: 1000,
    dayRateMax: 2000,
    avgDayRate: 1450,
    tier: 1,
    jobSearchTerms: ['%digital officer%', '%head of digital%', '%digital transformation%'],
    relatedRoles: ['fractional-cto', 'fractional-cmo'],
  },
  {
    acronym: 'CSO',
    fullTitle: 'Chief Strategy Officer',
    urlSlug: 'fractional-cso-chief-strategy-officer',
    department: 'Strategy',
    accentColor: 'cyan',
    dayRateMin: 1100,
    dayRateMax: 2200,
    avgDayRate: 1600,
    tier: 1,
    jobSearchTerms: ['%strategy officer%', '%chief strategy%', '%head of strategy%'],
    relatedRoles: ['fractional-ceo', 'fractional-coo'],
  },
  {
    acronym: 'CGO',
    fullTitle: 'Chief Growth Officer',
    urlSlug: 'fractional-cgo',
    department: 'Sales',
    accentColor: 'orange',
    dayRateMin: 1000,
    dayRateMax: 2000,
    avgDayRate: 1400,
    tier: 1,
    jobSearchTerms: ['%growth officer%', '%cgo%', '%head of growth%'],
    relatedRoles: ['fractional-cmo', 'fractional-cro'],
  },
  {
    acronym: 'CLO',
    fullTitle: 'Chief Legal Officer',
    urlSlug: 'fractional-clo-chief-legal-officer',
    department: 'Legal',
    accentColor: 'slate',
    dayRateMin: 1200,
    dayRateMax: 2500,
    avgDayRate: 1700,
    tier: 1,
    jobSearchTerms: ['%legal officer%', '%general counsel%', '%head of legal%', '%clo%'],
    relatedRoles: ['fractional-head-of-legal', 'fractional-cco-chief-compliance-officer'],
  },
  {
    acronym: 'CXO',
    fullTitle: 'Chief Experience Officer',
    urlSlug: 'fractional-cxo',
    department: 'Design',
    accentColor: 'indigo',
    dayRateMin: 900,
    dayRateMax: 1800,
    avgDayRate: 1300,
    tier: 1,
    jobSearchTerms: ['%experience officer%', '%cxo%', '%head of experience%', '%customer experience%director%'],
    relatedRoles: ['fractional-cmo', 'fractional-cpo'],
  },
  {
    acronym: 'CPO',
    fullTitle: 'Chief People Officer',
    urlSlug: 'fractional-cpo-chief-people-officer',
    department: 'HR',
    accentColor: 'violet',
    dayRateMin: 900,
    dayRateMax: 1800,
    avgDayRate: 1250,
    tier: 1,
    jobSearchTerms: ['%people officer%', '%chief people%', '%head of people%'],
    relatedRoles: ['fractional-chro', 'fractional-cdo-chief-diversity-officer'],
  },
  {
    acronym: '',
    fullTitle: 'Head of Legal',
    urlSlug: 'fractional-head-of-legal',
    department: 'Legal',
    accentColor: 'slate',
    dayRateMin: 800,
    dayRateMax: 1800,
    avgDayRate: 1200,
    tier: 1,
    jobSearchTerms: ['%head of legal%', '%legal director%', '%legal counsel%'],
    relatedRoles: ['fractional-clo-chief-legal-officer', 'fractional-cco-chief-compliance-officer'],
  },

  // === TIER 2: Solid Relevance (10 roles) ===
  {
    acronym: 'CCO',
    fullTitle: 'Chief Compliance Officer',
    urlSlug: 'fractional-cco-chief-compliance-officer',
    department: 'Compliance',
    accentColor: 'red',
    dayRateMin: 900,
    dayRateMax: 1800,
    avgDayRate: 1300,
    tier: 2,
    jobSearchTerms: ['%compliance officer%', '%head of compliance%', '%regulatory%officer%'],
    relatedRoles: ['fractional-clo-chief-legal-officer', 'fractional-cro-chief-risk-officer'],
  },
  {
    acronym: 'CSO',
    fullTitle: 'Chief Security Officer',
    urlSlug: 'fractional-cso-chief-security-officer',
    department: 'Compliance',
    accentColor: 'red',
    dayRateMin: 1000,
    dayRateMax: 2000,
    avgDayRate: 1450,
    tier: 2,
    jobSearchTerms: ['%security officer%', '%cso%security%', '%head of security%'],
    relatedRoles: ['fractional-ciso', 'fractional-ctso'],
  },
  {
    acronym: 'CBO',
    fullTitle: 'Chief Business Officer',
    urlSlug: 'fractional-cbo-chief-business-officer',
    department: 'Sales',
    accentColor: 'orange',
    dayRateMin: 1000,
    dayRateMax: 2000,
    avgDayRate: 1400,
    tier: 2,
    jobSearchTerms: ['%business officer%', '%cbo%', '%head of business%operations%'],
    relatedRoles: ['fractional-coo', 'fractional-cco-chief-commercial-officer'],
  },
  {
    acronym: 'CDO',
    fullTitle: 'Chief Diversity Officer',
    urlSlug: 'fractional-cdo-chief-diversity-officer',
    department: 'HR',
    accentColor: 'violet',
    dayRateMin: 800,
    dayRateMax: 1600,
    avgDayRate: 1100,
    tier: 2,
    jobSearchTerms: ['%diversity%officer%', '%inclusion%officer%', '%dei%', '%head of diversity%'],
    relatedRoles: ['fractional-chro', 'fractional-cpo-chief-people-officer'],
  },
  {
    acronym: 'CSO',
    fullTitle: 'Chief Sustainability Officer',
    urlSlug: 'fractional-cso-chief-sustainability-officer',
    department: 'Sustainability',
    accentColor: 'green',
    dayRateMin: 900,
    dayRateMax: 1800,
    avgDayRate: 1250,
    tier: 2,
    jobSearchTerms: ['%sustainability%officer%', '%esg%officer%', '%head of sustainability%'],
    relatedRoles: ['fractional-coo', 'fractional-cco-chief-compliance-officer'],
  },
  {
    acronym: 'CRO',
    fullTitle: 'Chief Risk Officer',
    urlSlug: 'fractional-cro-chief-risk-officer',
    department: 'Finance',
    accentColor: 'emerald',
    dayRateMin: 1000,
    dayRateMax: 2200,
    avgDayRate: 1500,
    tier: 2,
    jobSearchTerms: ['%risk officer%', '%head of risk%', '%risk management%director%'],
    relatedRoles: ['fractional-cfo', 'fractional-cco-chief-compliance-officer'],
  },
  {
    acronym: 'CINO',
    fullTitle: 'Chief Innovation Officer',
    urlSlug: 'fractional-cino',
    department: 'Innovation',
    accentColor: 'teal',
    dayRateMin: 1000,
    dayRateMax: 2000,
    avgDayRate: 1400,
    tier: 2,
    jobSearchTerms: ['%innovation officer%', '%cino%', '%head of innovation%'],
    relatedRoles: ['fractional-cto', 'fractional-cso-chief-strategy-officer'],
  },
  {
    acronym: 'CLO',
    fullTitle: 'Chief Learning Officer',
    urlSlug: 'fractional-clo-chief-learning-officer',
    department: 'HR',
    accentColor: 'violet',
    dayRateMin: 800,
    dayRateMax: 1600,
    avgDayRate: 1100,
    tier: 2,
    jobSearchTerms: ['%learning officer%', '%head of learning%', '%l&d director%', '%training director%'],
    relatedRoles: ['fractional-chro', 'fractional-cpo-chief-people-officer'],
  },
  {
    acronym: 'CBDO',
    fullTitle: 'Chief Business Development Officer',
    urlSlug: 'fractional-cbdo',
    department: 'Sales',
    accentColor: 'orange',
    dayRateMin: 900,
    dayRateMax: 1800,
    avgDayRate: 1300,
    tier: 2,
    jobSearchTerms: ['%business development%officer%', '%cbdo%', '%head of business development%'],
    relatedRoles: ['fractional-cro', 'fractional-cgo'],
  },
  {
    acronym: 'CIO',
    fullTitle: 'Chief Investment Officer',
    urlSlug: 'fractional-cio-chief-investment-officer',
    department: 'Finance',
    accentColor: 'emerald',
    dayRateMin: 1200,
    dayRateMax: 2500,
    avgDayRate: 1800,
    tier: 2,
    jobSearchTerms: ['%investment officer%', '%head of investments%', '%portfolio%officer%'],
    relatedRoles: ['fractional-cfo', 'fractional-cro-chief-risk-officer'],
  },

  // === TIER 3: Niche / Emerging (21 roles) ===
  {
    acronym: 'CCO',
    fullTitle: 'Chief Communications Officer',
    urlSlug: 'fractional-cco-chief-communications-officer',
    department: 'Communications',
    accentColor: 'pink',
    dayRateMin: 800,
    dayRateMax: 1700,
    avgDayRate: 1200,
    tier: 3,
    jobSearchTerms: ['%communications officer%', '%head of communications%', '%comms director%'],
    relatedRoles: ['fractional-cmo', 'fractional-cco-chief-content-officer'],
  },
  {
    acronym: 'CCO',
    fullTitle: 'Chief Content Officer',
    urlSlug: 'fractional-cco-chief-content-officer',
    department: 'Marketing',
    accentColor: 'amber',
    dayRateMin: 800,
    dayRateMax: 1600,
    avgDayRate: 1100,
    tier: 3,
    jobSearchTerms: ['%content officer%', '%head of content%', '%content director%'],
    relatedRoles: ['fractional-cmo', 'fractional-cco-chief-creative-officer'],
  },
  {
    acronym: 'CCO',
    fullTitle: 'Chief Creative Officer',
    urlSlug: 'fractional-cco-chief-creative-officer',
    department: 'Marketing',
    accentColor: 'amber',
    dayRateMin: 900,
    dayRateMax: 1800,
    avgDayRate: 1300,
    tier: 3,
    jobSearchTerms: ['%creative officer%', '%creative director%', '%head of creative%'],
    relatedRoles: ['fractional-cmo', 'fractional-cdo-chief-design-officer'],
  },
  {
    acronym: 'CCO',
    fullTitle: 'Chief Customer Officer',
    urlSlug: 'fractional-cco-chief-customer-officer',
    department: 'Communications',
    accentColor: 'pink',
    dayRateMin: 800,
    dayRateMax: 1700,
    avgDayRate: 1200,
    tier: 3,
    jobSearchTerms: ['%customer officer%', '%head of customer%', '%customer success%director%'],
    relatedRoles: ['fractional-cmo', 'fractional-cxo'],
  },
  {
    acronym: 'CDO',
    fullTitle: 'Chief Design Officer',
    urlSlug: 'fractional-cdo-chief-design-officer',
    department: 'Design',
    accentColor: 'indigo',
    dayRateMin: 900,
    dayRateMax: 1800,
    avgDayRate: 1300,
    tier: 3,
    jobSearchTerms: ['%design officer%', '%head of design%', '%design director%'],
    relatedRoles: ['fractional-cxo', 'fractional-cpo'],
  },
  {
    acronym: 'CSO',
    fullTitle: 'Chief Scientific Officer',
    urlSlug: 'fractional-cso-chief-scientific-officer',
    department: 'Innovation',
    accentColor: 'teal',
    dayRateMin: 1100,
    dayRateMax: 2200,
    avgDayRate: 1600,
    tier: 3,
    jobSearchTerms: ['%scientific officer%', '%head of science%', '%research director%'],
    relatedRoles: ['fractional-cro-chief-research-officer', 'fractional-cino'],
  },
  {
    acronym: 'CSO',
    fullTitle: 'Chief Services Officer',
    urlSlug: 'fractional-cso-chief-services-officer',
    department: 'Communications',
    accentColor: 'pink',
    dayRateMin: 800,
    dayRateMax: 1600,
    avgDayRate: 1100,
    tier: 3,
    jobSearchTerms: ['%services officer%', '%head of services%', '%service delivery%director%'],
    relatedRoles: ['fractional-coo', 'fractional-cco-chief-customer-officer'],
  },
  {
    acronym: 'CSO',
    fullTitle: 'Chief Solutions Officer',
    urlSlug: 'fractional-cso-chief-solutions-officer',
    department: 'Strategy',
    accentColor: 'cyan',
    dayRateMin: 900,
    dayRateMax: 1800,
    avgDayRate: 1300,
    tier: 3,
    jobSearchTerms: ['%solutions officer%', '%head of solutions%', '%solutions architect%'],
    relatedRoles: ['fractional-cto', 'fractional-cso-chief-strategy-officer'],
  },
  {
    acronym: 'CAO',
    fullTitle: 'Chief Administrative Officer',
    urlSlug: 'fractional-cao-chief-administrative-officer',
    department: 'Operations',
    accentColor: 'purple',
    dayRateMin: 800,
    dayRateMax: 1600,
    avgDayRate: 1100,
    tier: 3,
    jobSearchTerms: ['%administrative officer%', '%cao%', '%head of administration%'],
    relatedRoles: ['fractional-coo', 'fractional-chro'],
  },
  {
    acronym: 'CAO',
    fullTitle: 'Chief Analytics Officer',
    urlSlug: 'fractional-cao-chief-analytics-officer',
    department: 'Strategy',
    accentColor: 'cyan',
    dayRateMin: 1000,
    dayRateMax: 2000,
    avgDayRate: 1400,
    tier: 3,
    jobSearchTerms: ['%analytics officer%', '%head of analytics%', '%data analytics%director%'],
    relatedRoles: ['fractional-cdo-chief-data-officer', 'fractional-cto'],
  },
  {
    acronym: 'CBO',
    fullTitle: 'Chief Brand Officer',
    urlSlug: 'fractional-cbo-chief-brand-officer',
    department: 'Marketing',
    accentColor: 'amber',
    dayRateMin: 900,
    dayRateMax: 1800,
    avgDayRate: 1300,
    tier: 3,
    jobSearchTerms: ['%brand officer%', '%head of brand%', '%brand director%'],
    relatedRoles: ['fractional-cmo', 'fractional-cco-chief-creative-officer'],
  },
  {
    acronym: 'CPO',
    fullTitle: 'Chief Privacy Officer',
    urlSlug: 'fractional-cpo-chief-privacy-officer',
    department: 'Compliance',
    accentColor: 'red',
    dayRateMin: 900,
    dayRateMax: 1800,
    avgDayRate: 1300,
    tier: 3,
    jobSearchTerms: ['%privacy officer%', '%data protection%officer%', '%dpo%', '%head of privacy%'],
    relatedRoles: ['fractional-ciso', 'fractional-cco-chief-compliance-officer'],
  },
  {
    acronym: 'CPO',
    fullTitle: 'Chief Process Officer',
    urlSlug: 'fractional-cpo-chief-process-officer',
    department: 'Operations',
    accentColor: 'purple',
    dayRateMin: 800,
    dayRateMax: 1600,
    avgDayRate: 1100,
    tier: 3,
    jobSearchTerms: ['%process officer%', '%head of process%', '%process improvement%director%'],
    relatedRoles: ['fractional-coo', 'fractional-cqo'],
  },
  {
    acronym: 'CRO',
    fullTitle: 'Chief Reputation Officer',
    urlSlug: 'fractional-cro-chief-reputation-officer',
    department: 'Sustainability',
    accentColor: 'green',
    dayRateMin: 800,
    dayRateMax: 1700,
    avgDayRate: 1200,
    tier: 3,
    jobSearchTerms: ['%reputation%officer%', '%head of reputation%', '%corporate affairs%'],
    relatedRoles: ['fractional-cmo', 'fractional-cco-chief-communications-officer'],
  },
  {
    acronym: 'CRO',
    fullTitle: 'Chief Research Officer',
    urlSlug: 'fractional-cro-chief-research-officer',
    department: 'Innovation',
    accentColor: 'teal',
    dayRateMin: 1000,
    dayRateMax: 2000,
    avgDayRate: 1400,
    tier: 3,
    jobSearchTerms: ['%research officer%', '%head of research%', '%r&d director%'],
    relatedRoles: ['fractional-cso-chief-scientific-officer', 'fractional-cino'],
  },
  {
    acronym: 'CRO',
    fullTitle: 'Chief Restructuring Officer',
    urlSlug: 'fractional-cro-chief-restructuring-officer',
    department: 'Legal',
    accentColor: 'slate',
    dayRateMin: 1200,
    dayRateMax: 2500,
    avgDayRate: 1800,
    tier: 3,
    jobSearchTerms: ['%restructuring%officer%', '%turnaround%', '%insolvency%director%'],
    relatedRoles: ['fractional-cfo', 'fractional-clo-chief-legal-officer'],
  },
  {
    acronym: 'CKO',
    fullTitle: 'Chief Knowledge Officer',
    urlSlug: 'fractional-cko',
    department: 'Innovation',
    accentColor: 'teal',
    dayRateMin: 800,
    dayRateMax: 1600,
    avgDayRate: 1100,
    tier: 3,
    jobSearchTerms: ['%knowledge officer%', '%head of knowledge%', '%knowledge management%'],
    relatedRoles: ['fractional-clo-chief-learning-officer', 'fractional-cino'],
  },
  {
    acronym: 'CQO',
    fullTitle: 'Chief Quality Officer',
    urlSlug: 'fractional-cqo',
    department: 'Operations',
    accentColor: 'purple',
    dayRateMin: 800,
    dayRateMax: 1600,
    avgDayRate: 1100,
    tier: 3,
    jobSearchTerms: ['%quality officer%', '%head of quality%', '%quality director%'],
    relatedRoles: ['fractional-coo', 'fractional-cpo-chief-process-officer'],
  },
  {
    acronym: 'CSCO',
    fullTitle: 'Chief Supply Chain Officer',
    urlSlug: 'fractional-csco',
    department: 'Operations',
    accentColor: 'purple',
    dayRateMin: 900,
    dayRateMax: 1800,
    avgDayRate: 1300,
    tier: 3,
    jobSearchTerms: ['%supply chain%officer%', '%head of supply chain%', '%logistics director%'],
    relatedRoles: ['fractional-coo', 'fractional-procurement'],
  },
  {
    acronym: 'CTSO',
    fullTitle: 'Chief Technology Security Officer',
    urlSlug: 'fractional-ctso',
    department: 'Compliance',
    accentColor: 'red',
    dayRateMin: 1000,
    dayRateMax: 2000,
    avgDayRate: 1400,
    tier: 3,
    jobSearchTerms: ['%technology security%officer%', '%ctso%', '%tech security%director%'],
    relatedRoles: ['fractional-ciso', 'fractional-cso-chief-security-officer'],
  },
  {
    acronym: 'CVO',
    fullTitle: 'Chief Visionary Officer',
    urlSlug: 'fractional-cvo',
    department: 'Executive',
    accentColor: 'yellow',
    dayRateMin: 1000,
    dayRateMax: 2000,
    avgDayRate: 1400,
    tier: 3,
    jobSearchTerms: ['%visionary%officer%', '%cvo%'],
    relatedRoles: ['fractional-ceo', 'fractional-cso-chief-strategy-officer'],
  },
]
